#include <open.mp> // Стандартные возможности Open MultiPlayer
#include <a_mysql> // Для работы с СуБД MySQL
#include <PawnINI> // Для работы с файлами
#include <uuid> // UUID (универсальный уникальный идентификатор) - это стандартизированная реализация генерации уникальных последовательностей байтов.

#pragma tabsize 2 // Табуляция (кол-во пробелов вложенности содержимого блоков)

/** headers server */
#include "server/macros.inc"
#include "server/consts.inc"

/** headers client */
#include "client/macros.inc"
#include "client/consts.inc"